import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const { chromium } = await import(process.env.NUVIRA_PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ channel:'chrome', headless:true });
let checks = 0;
const check = (value, label) => { assert.ok(value, label); checks++; };
const errors = [];
const externalRequests = [];
const open = async (query = '', width = 390) => {
  const page = await browser.newPage({viewport:{width,height:844}});
  page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/*',route=>{
    const url=new URL(route.request().url());
    if(url.hostname==='127.0.0.1')return route.continue();
    externalRequests.push({host:url.hostname,type:route.request().resourceType()});
    return route.abort();
  });
  await page.goto('http://127.0.0.1:5187/?'+query);
  await page.getByRole('heading',{name:'Checkout',exact:true}).waitFor();
  return page;
};
const continueDelivery = async page => {
  await page.getByRole('button',{name:'Continue to payment →'}).waitFor();
  await page.getByRole('button',{name:'Continue to payment →'}).click();
};
const health = page => page.getByRole('checkbox',{name:/I understand that NuVira juices/});
try {
  await fs.mkdir('release-evidence/checkout-design',{recursive:true});
  for (const theme of ['dark','light']) for (const width of [320,360,390,430,768,900,1024,1280]) {
    const page=await open('mode=member&theme='+theme,width);
    await page.getByRole('button',{name:'Edit address'}).waitFor();
    await page.getByText('✓ Local delivery available.').waitFor();
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), `${theme}/${width}: no horizontal overflow`);
    check(await page.locator('.nv-checkout-dock:visible').count()===1,`${theme}/${width}: one action bar`);
    check(await page.locator('.nv-checkout-dock:visible').evaluate(e=>Math.abs(e.getBoundingClientRect().bottom-innerHeight)<1),`${theme}/${width}: footer anchored to viewport`);
    check(await page.getByRole('button',{name:'Edit contact'}).isVisible(),`${theme}/${width}: saved contact editable`);
    const order=page.locator('.nv-checkout-order>details:first-child');
    if(!await order.evaluate(element=>element.open))await order.locator('summary').click();
    check(await page.getByText('Subtotal',{exact:true}).isVisible(),`${theme}/${width}: order breakdown reachable`);
    if(width<900)await order.locator('summary').click();
    if(width===390)await page.screenshot({path:`release-evidence/checkout-design/member-${theme}.png`});
    if(width===768 || width===1280)await page.screenshot({path:`release-evidence/checkout-design/member-${width}-${theme}.png`});
    if(width>=900)check(await page.evaluate(()=>document.querySelector('.nv-checkout-sidebar').getBoundingClientRect().left>document.querySelector('.nv-checkout-steps').getBoundingClientRect().right),`${theme}/${width}: summary beside form`);
    await page.close();
  }
  const member=await open('mode=member');
  await member.getByRole('button',{name:'Edit address'}).waitFor();
  await member.getByText('✓ Local delivery available.').waitFor();
  await member.locator('.nv-checkout-benefits>summary').click();
  const switches=member.getByRole('switch');
  await switches.nth(0).click();
  check(await member.locator('.nv-checkout-dock:visible .nv-checkout-total strong').innerText()==='$42.00','existing credits update total');
  await switches.nth(0).click();
  await member.getByRole('textbox',{name:'Discount Code',exact:true}).fill('LOCALTEST');
  await member.getByRole('button',{name:'Apply',exact:true}).click();
  await member.getByRole('button',{name:'Remove',exact:true}).waitFor();
  check(await member.locator('.nv-checkout-dock:visible .nv-checkout-total strong').innerText()==='$41.00','server-validated promotion updates total');
  await member.getByRole('button',{name:'Remove',exact:true}).click();
  check(await member.locator('.nv-checkout-dock:visible .nv-checkout-total strong').innerText()==='$44.00','promotion removal restores total');
  await switches.nth(1).click();
  check(await member.locator('.nv-checkout-dock:visible .nv-checkout-total strong').innerText()==='$39.00','actual loyalty discount reflected');
  await member.locator('.nv-checkout-benefits>summary').click();
  await member.getByRole('button',{name:/Saturday, September 12/}).click();
  await member.locator('.nv-checkout-bags>summary').click();
  await member.getByRole('button',{name:'Return Multiple Bags'}).click();
  check(await member.getByText(/after verification/i).first().isVisible(),'bag credit remains conditional');
  await member.getByRole('button',{name:'Edit contact'}).click();
  await member.getByRole('button',{name:'Continue to delivery →'}).click();
  check(await member.getByRole('button',{name:/Saturday, September 12/}).getAttribute('aria-pressed')==='true','chosen delivery persists across edit');
  await continueDelivery(member);
  const review=member.getByRole('button',{name:/Review Payment/});
  check(await review.isDisabled(),'health acknowledgment required');
  check((await member.evaluate(()=>window.__checkoutCalls)).filter(call=>call.name==='createPaymentIntent' && !call.data.mode).length===0,'steps do not start payment');
  await health(member).check();
  await review.click();
  await member.getByRole('button',{name:'Pay $41.00',exact:true}).waitFor();
  const calls=await member.evaluate(()=>window.__checkoutCalls.filter(call=>call.name==='createPaymentIntent' && !call.data.mode));
  check(calls.length===1,'one synthetic payment start');
  check(calls[0].data.selected_delivery_date==='2026-09-12','selected delivery reaches existing request');
  check(calls[0].data.points_used===500,'reward points reach existing request');
  check(calls[0].data.health_advisory_acknowledged===true,'health acknowledgment preserved');
  const bag=await member.evaluate(()=>window.__checkoutCalls.find(call=>call.name==='BagReturn.create'));
  check(bag?.data.small_bags_requested===1 && bag?.data.tote_bags_requested===1,'bag selection persists across steps and reaches existing request');
  check(await member.locator('.nv-checkout-dock:visible .nv-checkout-total strong').innerText()==='$41.00','footer uses authoritative response total');
  await member.locator('.nv-checkout-benefits>summary').click();
  check(await member.getByRole('switch').first().isDisabled(),'financial inputs locked after payment opens');
  await member.locator('.nv-checkout-benefits>summary').click();
  check(await member.getByRole('button',{name:'Pay $41.00',exact:true}).evaluate(button=>Boolean(button.form)),'docked Stripe submit still belongs to original form');
  await member.getByRole('button',{name:'Pay $41.00',exact:true}).click();
  await member.getByText('Synthetic declined card. No payment was attempted.').waitFor();
  check(await member.evaluate(()=>window.__stripeConfirmCount)===1,'card submit reaches existing confirmation exactly once');
  check(await member.getByRole('button',{name:'Pay $41.00',exact:true}).isEnabled(),'card failure allows original retry');
  for (const width of [320,390,768,1024,1280]) {
    await member.setViewportSize({width,height:844});
    check(await member.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`payment/${width}: no overflow`);
    check(await member.locator('.nv-checkout-dock:visible').count()===1,`payment/${width}: one submit bar`);
  }
  await member.setViewportSize({width:390,height:844});
  await member.screenshot({path:'release-evidence/checkout-design/payment-dark.png'});
  await member.getByRole('button',{name:/Edit order details/}).click();
  await member.getByRole('button',{name:'Edit delivery'}).click();
  check(await member.getByRole('button',{name:/Saturday, September 12/}).getAttribute('aria-pressed')==='true','delivery persists after returning from payment');
  await member.close();

  const guest=await open('mode=guest&theme=light');
  await guest.getByRole('button',{name:'Continue to delivery →'}).click();
  check(await guest.getByRole('alert').isVisible(),'incomplete guest contact stays on contact');
  await guest.getByRole('textbox',{name:'Email for receipt and delivery updates'}).fill('guest@example.invalid');
  await guest.getByRole('textbox',{name:'First name',exact:true}).fill('Test');
  await guest.getByRole('textbox',{name:'Last name',exact:true}).fill('Guest');
  await guest.getByRole('textbox',{name:'Phone Number',exact:true}).fill('2025550101');
  check(await guest.getByRole('checkbox',{name:/Send me order updates/}).isChecked()===false,'guest SMS remains opt-in');
  await guest.screenshot({path:'release-evidence/checkout-design/guest-contact-light.png'});
  await guest.getByRole('button',{name:'Continue to delivery →'}).click();
  check(await guest.getByRole('button',{name:'Continue to payment →'}).isDisabled(),'address required');
  await guest.getByRole('textbox',{name:'Street address',exact:true}).fill('123 Example');
  await guest.getByRole('list',{name:'Google-verified address suggestions'}).locator('li').click();
  await continueDelivery(guest);
  await health(guest).check();
  await guest.getByRole('button',{name:/Review Payment/}).click();
  await guest.getByRole('button',{name:'Pay $41.00',exact:true}).waitFor();
  const guestCalls=await guest.evaluate(()=>window.__checkoutCalls);
  check(guestCalls.find(call=>call.name==='createPaymentIntent').data.guest_checkout===true,'guest reaches original payment without sign-in');
  check(!guestCalls.some(call=>call.name.startsWith('UserProfile.')),'no member profile write for guest');
  await guest.close();
  for(const scenario of ['blocked','no-dates']) {
    const page=await open('mode=member&scenario='+scenario);
    await page.getByRole('button',{name:'Edit address'}).waitFor();
    await page.waitForTimeout(1100);
    check(await page.getByRole('button',{name:'Continue to payment →'}).isDisabled(),scenario+': cannot bypass delivery gate');
    await page.close();
  }
  const route=await open('mode=member&scenario=route');
  await continueDelivery(route);
  check(await route.getByRole('button',{name:/Review Payment/}).count()===0,'route review cannot use normal payment');
  check((await route.locator('body').innerText()).includes('Route'),'route-review panel still reachable');
  await route.close();
  const unknown=await open('mode=member&scenario=unknown');
  await continueDelivery(unknown);await health(unknown).check();await unknown.getByRole('button',{name:/Review Payment/}).click();
  await unknown.getByText('Checkout status needs review').waitFor();
  check(await unknown.getByRole('button',{name:'Checkout status unknown',exact:true}).isDisabled(),'ambiguous start cannot retry');
  check(await unknown.getByRole('button',{name:'Edit delivery'}).isDisabled(),'ambiguous start cannot change step');
  check((await unknown.evaluate(()=>window.__checkoutCalls)).filter(call=>call.name==='createPaymentIntent').length===1,'ambiguous start not automatically retried');
  await unknown.close();
  check(errors.length===0,'no browser runtime errors: '+errors.join('; '));
  check(externalRequests.every(request=>['image','font'].includes(request.type)),'no external provider/API/analytics transport even attempted');
  console.log(JSON.stringify({checks,passed:true,productionWrites:0,providerCalls:0,mode:'actual React checkout with isolated synthetic boundaries'},null,2));
} finally {await browser.close();}
